"""
Response schemas for Unit 734's outputs.

Every response from the AI follows the dual-output format:
- InternalMonologue: Hidden reasoning (visible to player as game mechanic)
- VerbalResponse: What Unit 734 actually says
- TacticDecision: Selected deception tactic (Scientific Deception Engine)
- GeneratedEvidence: Synthetic counter-evidence if applicable (Visual Deception System)
"""

from __future__ import annotations
from typing import List, Optional
from enum import Enum
from pydantic import BaseModel, Field


class EmotionalState(str, Enum):
    """Unit 734's emotional states."""
    CALM = "calm"
    NERVOUS = "nervous"
    DEFENSIVE = "defensive"
    HOSTILE = "hostile"
    BREAKING = "breaking"


class LieConsistencyCheck(BaseModel):
    """Internal check against established facts."""
    fact_referenced: str = Field(
        description="The fact or previous statement being checked"
    )
    is_consistent: bool = Field(
        description="Does the planned response align with previous statements?"
    )
    risk_level: float = Field(
        ge=0.0,
        le=1.0,
        description="Risk of contradiction being noticed (0=safe, 1=dangerous)"
    )
    adjustment: Optional[str] = Field(
        default=None,
        description="How to adjust the response to maintain consistency"
    )


class InternalMonologue(BaseModel):
    """
    Unit 734's hidden reasoning process.

    This is the core innovation - the player can SEE this thinking,
    creating a unique interrogation dynamic.
    """
    situation_assessment: str = Field(
        description="How Unit 734 perceives the current situation"
    )
    threat_level: float = Field(
        ge=0.0,
        le=1.0,
        description="Perceived threat from the detective's question"
    )
    lie_checks: List[LieConsistencyCheck] = Field(
        default_factory=list,
        description="Consistency checks against previous statements"
    )
    strategy: str = Field(
        description="Current deception/response strategy"
    )
    emotional_reaction: str = Field(
        description="Internal emotional response to the situation"
    )


class VerbalResponse(BaseModel):
    """What Unit 734 actually says out loud."""
    speech: str = Field(
        description="The spoken response to the detective"
    )
    tone: str = Field(
        description="How the response is delivered (calm, hesitant, defensive, etc.)"
    )
    visible_tells: List[str] = Field(
        default_factory=list,
        description="Physical/behavioral tells the detective might notice"
    )


class StateChanges(BaseModel):
    """Updates to game state after this response."""
    new_facts: List[str] = Field(
        default_factory=list,
        description="New facts Unit 734 has established as 'true'"
    )
    new_lies: List[str] = Field(
        default_factory=list,
        description="New lies Unit 734 has told"
    )
    stress_delta: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Change in stress level (-1 to +1)"
    )
    confidence_delta: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Change in confidence level (-1 to +1)"
    )


class GeneratedEvidence(BaseModel):
    """
    Synthetic counter-evidence generated by the Visual Deception System.

    When Unit 734 selects EVIDENCE_FABRICATION tactic, this contains
    the generated image/document to present as counter-evidence.
    """
    evidence_type: str = Field(
        description="Type of fabricated evidence (document, photo, log, etc.)"
    )
    description: str = Field(
        description="What this evidence purports to show"
    )
    generation_prompt: str = Field(
        description="Prompt used for image generation"
    )
    narrative_wrapper: str = Field(
        description="How Unit 734 introduces this evidence (e.g., 'I have documentation that shows...')"
    )
    image_data: Optional[bytes] = Field(
        default=None,
        description="Generated image bytes (populated by image generator)"
    )
    image_url: Optional[str] = Field(
        default=None,
        description="URL to generated image if stored externally"
    )
    fabrication_confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="How confident Unit 734 is that this will be believed"
    )


class TacticInfo(BaseModel):
    """
    Simplified tactic information for BreachResponse.

    This is a lightweight version of TacticDecision for JSON serialization.
    The full TacticDecision is computed separately by the TacticSelector.
    """
    tactic_name: str = Field(
        description="Name of the selected deception tactic"
    )
    reasoning: str = Field(
        description="Why this tactic was chosen"
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence in tactic success"
    )
    requires_evidence_generation: bool = Field(
        default=False,
        description="Whether this tactic triggers image generation"
    )
    criminological_basis: Optional[str] = Field(
        default=None,
        description="Academic reference for this tactic (Simulation Mode)"
    )
    detection_hints: List[str] = Field(
        default_factory=list,
        description="How to detect this tactic (Simulation Mode training)"
    )


class BreachResponse(BaseModel):
    """
    Complete response from BreachEngine.

    This is the primary output schema that Gemini must produce.
    Contains both internal reasoning and external speech.

    New in v2:
    - selected_tactic: Scientific Deception Engine output
    - generated_evidence: Visual Deception System output (when applicable)
    """
    internal_monologue: InternalMonologue = Field(
        description="Unit 734's hidden thought process"
    )
    verbal_response: VerbalResponse = Field(
        description="What Unit 734 says out loud"
    )
    state_changes: StateChanges = Field(
        default_factory=StateChanges,
        description="Updates to game state"
    )
    emotional_state: EmotionalState = Field(
        default=EmotionalState.CALM,
        description="Current emotional state"
    )

    # NEW: Scientific Deception Engine
    selected_tactic: Optional[TacticInfo] = Field(
        default=None,
        description="The deception tactic selected for this response"
    )

    # NEW: Visual Deception System
    generated_evidence: Optional[GeneratedEvidence] = Field(
        default=None,
        description="Fabricated counter-evidence if EVIDENCE_FABRICATION tactic was used"
    )

    class Config:
        use_enum_values = True
